/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MiniPCController;
import Model.BCP;
import Model.CPU;
import Model.FileManager;
import Model.Memory;
import Model.MemoryRegister;
import Model.StatsSet;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author aleja
 */
public class MiniPC extends javax.swing.JFrame {
    // Esta clase representa la GUI del programa que se utiliza para cargar los archivos, leer las instrucciones y ver la información de la memoria y los registros
    // Contiene el controlador del CPU, el administrador de archivos, la cantidad de filas de instrucciones que se han generado y la dirección actual que se desplegará en la GUI
    
    public MiniPCController controller = new MiniPCController();
    public MiniPCController controller2 = new MiniPCController();
    public FileManager fileManager = new FileManager();
    boolean waitingForInput = false;
    boolean archivoAbierto = false;
    boolean jumpFlag = false;
    boolean isAutomatic = false;
    int jumpToAddress = 0;
    
    /**
     * Creates new form NewJFrame
     */
    public MiniPC() {
        CPU cpu = new CPU("CPU #0");
        Memory memory = new Memory();
        cpu.setMemory(memory);
        
        CPU cpu2 = new CPU("CPU #1");
        Memory memory2 = new Memory();
        cpu2.setMemory(memory2);
        
        this.getController().setCpu(cpu);
        this.getController2().setCpu(cpu2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextInstructionBtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Pnl_Registros = new javax.swing.JPanel();
        lblAX = new javax.swing.JLabel();
        lblNumberAX = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        lblNumberPC = new javax.swing.JLabel();
        lblBX = new javax.swing.JLabel();
        lblNumberBX = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblNumberAC = new javax.swing.JLabel();
        lblCX = new javax.swing.JLabel();
        lblNumberCX = new javax.swing.JLabel();
        lblDX = new javax.swing.JLabel();
        lblNumberDX = new javax.swing.JLabel();
        lblIR = new javax.swing.JLabel();
        lblNumberIR = new javax.swing.JLabel();
        lblAL = new javax.swing.JLabel();
        lblNumberAL = new javax.swing.JLabel();
        lblAH = new javax.swing.JLabel();
        lblNumberAH = new javax.swing.JLabel();
        Pnl_Memoria = new javax.swing.JScrollPane();
        tblCode = new javax.swing.JTable();
        Pnl_Menu = new javax.swing.JPanel();
        loadFileBtn = new javax.swing.JButton();
        cleanTableBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        lblTeclado = new javax.swing.JLabel();
        nextInstructionBtn = new javax.swing.JButton();
        tecladoTxtField = new javax.swing.JTextField();
        lblPantalla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JTextPane();
        automaticBtn = new javax.swing.JButton();
        cleanTableBtn1 = new javax.swing.JButton();
        cleanTableBtn2 = new javax.swing.JButton();
        Lbl_memoria = new javax.swing.JLabel();
        Lbl_registros = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lbl_registros1 = new javax.swing.JLabel();
        Pnl_Registros1 = new javax.swing.JPanel();
        lblAX1 = new javax.swing.JLabel();
        lblNumberAX1 = new javax.swing.JLabel();
        lblPC1 = new javax.swing.JLabel();
        lblNumberPC1 = new javax.swing.JLabel();
        lblBX1 = new javax.swing.JLabel();
        lblNumberBX1 = new javax.swing.JLabel();
        lblAC1 = new javax.swing.JLabel();
        lblNumberAC1 = new javax.swing.JLabel();
        lblCX1 = new javax.swing.JLabel();
        lblNumberCX1 = new javax.swing.JLabel();
        lblDX1 = new javax.swing.JLabel();
        lblNumberDX1 = new javax.swing.JLabel();
        lblIR1 = new javax.swing.JLabel();
        lblNumberIR1 = new javax.swing.JLabel();
        lblAL1 = new javax.swing.JLabel();
        lblNumberAL1 = new javax.swing.JLabel();
        lblAH1 = new javax.swing.JLabel();
        lblNumberAH1 = new javax.swing.JLabel();
        Lbl_memoria1 = new javax.swing.JLabel();
        Pnl_Memoria1 = new javax.swing.JScrollPane();
        tblCode1 = new javax.swing.JTable();
        Pnl_Memoria2 = new javax.swing.JScrollPane();
        tblCode2 = new javax.swing.JTable();
        Lbl_memoria2 = new javax.swing.JLabel();
        Lbl_memoria3 = new javax.swing.JLabel();
        Pnl_Memoria3 = new javax.swing.JScrollPane();
        tblCode3 = new javax.swing.JTable();

        nextInstructionBtn1.setText("Siguiente instrucción");
        nextInstructionBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniPC");

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 450));
        jPanel3.setRequestFocusEnabled(false);

        Pnl_Registros.setBackground(new java.awt.Color(204, 204, 255));

        lblAX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAX.setText("AX:");

        lblNumberAX.setText("0");

        lblPC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPC.setText("PC: ");

        lblNumberPC.setText("0");

        lblBX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBX.setText("BX:");

        lblNumberBX.setText("0");

        lblAC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAC.setText("AC:");

        lblNumberAC.setText("0");

        lblCX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCX.setText("CX:");

        lblNumberCX.setText("0");

        lblDX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDX.setText("DX: ");

        lblNumberDX.setText("0");

        lblIR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIR.setText("IR:");

        lblNumberIR.setText(" ");

        lblAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAL.setText("AL:");

        lblNumberAL.setText("0");

        lblAH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAH.setText("AH:");

        lblNumberAH.setText("0");

        javax.swing.GroupLayout Pnl_RegistrosLayout = new javax.swing.GroupLayout(Pnl_Registros);
        Pnl_Registros.setLayout(Pnl_RegistrosLayout);
        Pnl_RegistrosLayout.setHorizontalGroup(
            Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                        .addComponent(lblAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumberAL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                        .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addComponent(lblAX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumberAX))
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addComponent(lblPC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumberPC)))
                        .addGap(87, 87, 87)
                        .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAC)
                                    .addComponent(lblBX))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumberBX)
                                    .addComponent(lblNumberAC))
                                .addGap(35, 35, 35))
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblAH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumberAH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addComponent(lblDX)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addComponent(lblIR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumberDX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumberIR, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addComponent(lblCX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumberCX)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        Pnl_RegistrosLayout.setVerticalGroup(
            Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAX)
                    .addComponent(lblNumberAX)
                    .addComponent(lblBX)
                    .addComponent(lblNumberBX)
                    .addComponent(lblCX)
                    .addComponent(lblNumberCX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC)
                    .addComponent(lblNumberPC)
                    .addComponent(lblAC)
                    .addComponent(lblNumberAC)
                    .addComponent(lblIR)
                    .addComponent(lblNumberIR)
                    .addComponent(lblNumberDX))
                .addGap(7, 7, 7)
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAH)
                        .addComponent(lblNumberAH)
                        .addComponent(lblDX))
                    .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAL)
                        .addComponent(lblNumberAL)))
                .addContainerGap())
        );

        Pnl_Memoria.setBackground(new java.awt.Color(204, 204, 255));
        Pnl_Memoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pnl_Memoria.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pnl_Memoria.setMaximumSize(new java.awt.Dimension(102, 102));
        Pnl_Memoria.setMinimumSize(new java.awt.Dimension(101, 101));
        Pnl_Memoria.setName(""); // NOI18N

        tblCode.setBackground(new java.awt.Color(204, 204, 255));
        tblCode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Nombre", "Estado"
            }
        ));
        tblCode.setRowHeight(30);
        Pnl_Memoria.setViewportView(tblCode);

        Pnl_Menu.setBackground(new java.awt.Color(204, 204, 255));
        Pnl_Menu.setPreferredSize(new java.awt.Dimension(602, 602));

        loadFileBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        loadFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/archivo.png"))); // NOI18N
        loadFileBtn.setText("Cargar Archivo");
        loadFileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loadFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileBtnActionPerformed(evt);
            }
        });

        cleanTableBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cleanTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reiniciar.png"))); // NOI18N
        cleanTableBtn.setText("Limpiar");
        cleanTableBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cleanTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanTableBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salir.png"))); // NOI18N
        exitBtn.setText("Salir");
        exitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        lblTeclado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTeclado.setText("Teclado");

        nextInstructionBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nextInstructionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/siguiente.png"))); // NOI18N
        nextInstructionBtn.setText("Siguiente");
        nextInstructionBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nextInstructionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtnActionPerformed(evt);
            }
        });

        tecladoTxtField.setEditable(false);
        tecladoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecladoTxtFieldActionPerformed(evt);
            }
        });

        lblPantalla.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPantalla.setText("Pantalla");

        jScrollPane1.setViewportView(pantalla);

        automaticBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        automaticBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/siguiente.png"))); // NOI18N
        automaticBtn.setText("Automático");
        automaticBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        automaticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticBtnActionPerformed(evt);
            }
        });

        cleanTableBtn1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cleanTableBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reiniciar.png"))); // NOI18N
        cleanTableBtn1.setText("Estadísticas");
        cleanTableBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cleanTableBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanTableBtn1ActionPerformed(evt);
            }
        });

        cleanTableBtn2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cleanTableBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reiniciar.png"))); // NOI18N
        cleanTableBtn2.setText("Configurar memoria");
        cleanTableBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cleanTableBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanTableBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_MenuLayout = new javax.swing.GroupLayout(Pnl_Menu);
        Pnl_Menu.setLayout(Pnl_MenuLayout);
        Pnl_MenuLayout.setHorizontalGroup(
            Pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPantalla)
                .addGap(38, 38, 38))
            .addGroup(Pnl_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextInstructionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFileBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(automaticBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tecladoTxtField)
                    .addComponent(cleanTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cleanTableBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cleanTableBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTeclado)
                .addGap(39, 39, 39))
        );
        Pnl_MenuLayout.setVerticalGroup(
            Pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTeclado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tecladoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(loadFileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextInstructionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(automaticBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cleanTableBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cleanTableBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cleanTableBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Lbl_memoria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_memoria.setText("Memoria");
        Lbl_memoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_registros.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_registros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_registros.setText("BCP CPU1");
        Lbl_registros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Mini PC");

        Lbl_registros1.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_registros1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_registros1.setText("BCP CPU2");
        Lbl_registros1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Pnl_Registros1.setBackground(new java.awt.Color(204, 204, 255));

        lblAX1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAX1.setText("AX:");

        lblNumberAX1.setText("0");

        lblPC1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPC1.setText("PC: ");

        lblNumberPC1.setText("0");

        lblBX1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBX1.setText("BX:");

        lblNumberBX1.setText("0");

        lblAC1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAC1.setText("AC:");

        lblNumberAC1.setText("0");

        lblCX1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCX1.setText("CX:");

        lblNumberCX1.setText("0");

        lblDX1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDX1.setText("DX: ");

        lblNumberDX1.setText("0");

        lblIR1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIR1.setText("IR:");

        lblNumberIR1.setText(" ");

        lblAL1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAL1.setText("AL:");

        lblNumberAL1.setText("0");

        lblAH1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAH1.setText("AH:");

        lblNumberAH1.setText("0");

        javax.swing.GroupLayout Pnl_Registros1Layout = new javax.swing.GroupLayout(Pnl_Registros1);
        Pnl_Registros1.setLayout(Pnl_Registros1Layout);
        Pnl_Registros1Layout.setHorizontalGroup(
            Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                        .addComponent(lblAL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumberAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                        .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                                .addComponent(lblAX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumberAX1))
                            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                                .addComponent(lblPC1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumberPC1)))
                        .addGap(87, 87, 87)
                        .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                                .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAC1)
                                    .addComponent(lblBX1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumberBX1)
                                    .addComponent(lblNumberAC1))
                                .addGap(35, 35, 35))
                            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblAH1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumberAH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                                .addComponent(lblDX1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                                .addComponent(lblIR1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumberDX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumberIR1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                                .addComponent(lblCX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumberCX1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        Pnl_Registros1Layout.setVerticalGroup(
            Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_Registros1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAX1)
                    .addComponent(lblNumberAX1)
                    .addComponent(lblBX1)
                    .addComponent(lblNumberBX1)
                    .addComponent(lblCX1)
                    .addComponent(lblNumberCX1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC1)
                    .addComponent(lblNumberPC1)
                    .addComponent(lblAC1)
                    .addComponent(lblNumberAC1)
                    .addComponent(lblIR1)
                    .addComponent(lblNumberIR1)
                    .addComponent(lblNumberDX1))
                .addGap(7, 7, 7)
                .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAH1)
                        .addComponent(lblNumberAH1)
                        .addComponent(lblDX1))
                    .addGroup(Pnl_Registros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAL1)
                        .addComponent(lblNumberAL1)))
                .addContainerGap())
        );

        Lbl_memoria1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_memoria1.setText("Memoria");
        Lbl_memoria1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Pnl_Memoria1.setBackground(new java.awt.Color(204, 204, 255));
        Pnl_Memoria1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pnl_Memoria1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pnl_Memoria1.setMaximumSize(new java.awt.Dimension(102, 102));
        Pnl_Memoria1.setMinimumSize(new java.awt.Dimension(101, 101));
        Pnl_Memoria1.setName(""); // NOI18N

        tblCode1.setBackground(new java.awt.Color(204, 204, 255));
        tblCode1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código ASM", "Código binario", "Address", "Tiempo"
            }
        ));
        tblCode1.setRowHeight(30);
        Pnl_Memoria1.setViewportView(tblCode1);
        if (tblCode1.getColumnModel().getColumnCount() > 0) {
            tblCode1.getColumnModel().getColumn(3).setHeaderValue("Tiempo");
        }

        Pnl_Memoria2.setBackground(new java.awt.Color(204, 204, 255));
        Pnl_Memoria2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pnl_Memoria2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pnl_Memoria2.setMaximumSize(new java.awt.Dimension(102, 102));
        Pnl_Memoria2.setMinimumSize(new java.awt.Dimension(101, 101));
        Pnl_Memoria2.setName(""); // NOI18N

        tblCode2.setBackground(new java.awt.Color(204, 204, 255));
        tblCode2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código ASM", "Código binario", "Address", "Tiempo"
            }
        ));
        tblCode2.setRowHeight(30);
        Pnl_Memoria2.setViewportView(tblCode2);
        if (tblCode2.getColumnModel().getColumnCount() > 0) {
            tblCode2.getColumnModel().getColumn(3).setHeaderValue("Tiempo");
        }

        Lbl_memoria2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_memoria2.setText("Lista de procesos");
        Lbl_memoria2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_memoria3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_memoria3.setText("Lista de procesos");
        Lbl_memoria3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Pnl_Memoria3.setBackground(new java.awt.Color(204, 204, 255));
        Pnl_Memoria3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pnl_Memoria3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pnl_Memoria3.setMaximumSize(new java.awt.Dimension(102, 102));
        Pnl_Memoria3.setMinimumSize(new java.awt.Dimension(101, 101));
        Pnl_Memoria3.setName(""); // NOI18N

        tblCode3.setBackground(new java.awt.Color(204, 204, 255));
        tblCode3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Nombre", "Estado"
            }
        ));
        tblCode3.setRowHeight(30);
        Pnl_Memoria3.setViewportView(tblCode3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(Lbl_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pnl_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(Lbl_memoria))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pnl_Memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pnl_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pnl_Memoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(Lbl_memoria2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Pnl_Memoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(Pnl_Registros1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(Lbl_registros1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(Lbl_memoria1)))
                    .addComponent(Pnl_Memoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Lbl_memoria3)))
                .addGap(32, 32, 32))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Lbl_registros1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pnl_Registros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lbl_memoria1)
                        .addGap(4, 4, 4)
                        .addComponent(Pnl_Memoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lbl_memoria2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pnl_Memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lbl_memoria3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pnl_Memoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Lbl_registros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Pnl_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Lbl_memoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pnl_Memoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pnl_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanTable(){
        // Este método limpia toda la tabla de instrucciones por medio de resetear todos los valores que están siendo actualmente desplegados
        // También resetea el controlador de CPU actual y el administrador de archivos actual
        // No recibe ningún parámetro
        
        for (int i = 0; i < this.getTblCode().getRowCount(); i++) {
                this.getTblCode().setValueAt("", i, 0);
                this.getTblCode().setValueAt("", i, 1);
                this.getTblCode().setValueAt("", i, 2);
                this.getTblCode().setValueAt("", i, 3);
        }
        this.getLblNumberAC().setText("0");
        this.getLblNumberPC().setText("0");
        this.getLblNumberIR().setText(" ");
        this.getLblNumberAX().setText("0");
        this.getLblNumberBX().setText("0");
        this.getLblNumberCX().setText("0");
        this.getLblNumberDX().setText("0");
        this.getController().setCpu(null);
        this.getController2().setCpu(null);
        FileManager newFileManager = new FileManager();
        this.setFileManager(newFileManager);
    }

    public boolean isJumpFlag() {
        return jumpFlag;
    }

    public void setJumpFlag(boolean jumpFlag) {
        this.jumpFlag = jumpFlag;
    }

    public int getJumpToAddress() {
        return jumpToAddress;
    }

    public void setJumpToAddress(int jumpToAddress) {
        this.jumpToAddress = jumpToAddress;
    }
    

    public boolean isWaitingForInput() {
        return waitingForInput;
    }

    public void setWaitingForInput(boolean waitingForInput) {
        this.waitingForInput = waitingForInput;
    }

    public boolean isArchivoAbierto() {
        return archivoAbierto;
    }

    public void setArchivoAbierto(boolean archivoAbierto) {
        this.archivoAbierto = archivoAbierto;
    }

    public MiniPCController getController2() {
        return controller2;
    }

    public void setController2(MiniPCController controller2) {
        this.controller2 = controller2;
    }
    
    
    
    public void updateTable(ArrayList<MemoryRegister> instructionSet,ArrayList<MemoryRegister> instructionSet2, int row) {
        // Este método actualiza la tabla visualmente, es decir actualiza la información que está siendo desplegada en la GUI
        // Va mostrando paso a paso las instrucciones cargadas en memoria y toda la información relevante a estas
        // Recibe como parámetros el set de instrucciones y el valor entero de la fila donde se desplegará la instrucción
        System.out.println(this.getController().getCpu().getCurrentAddress());
        System.out.println(this.getController().getCpu().getProgramCounter());
        System.out.println(this.getController2().getCpu().getCurrentAddress());
        System.out.println(this.getController2().getCpu().getProgramCounter());
        //cpu 1
        this.getTblCode().setValueAt(instructionSet.get(row).getAsmInstructionString(), this.getController().getCpu().getNumberExecutedInstructions(), 0);
        this.getTblCode().setValueAt(instructionSet.get(row).convertToBinary(), this.getController().getCpu().getNumberExecutedInstructions(), 1);
        this.getTblCode().setValueAt(this.getController().getCpu().getCurrentAddress(), this.getController().getCpu().getNumberExecutedInstructions(), 2);
        this.getTblCode().setValueAt(this.getController().getCpu().getCurrentTime(), this.getController().getCpu().getNumberExecutedInstructions(), 3);
        
        this.getLblNumberAX().setText(this.getController().getCpu().getDataRegisters().get(0).getValue()+"");
        this.getLblNumberBX().setText(this.getController().getCpu().getDataRegisters().get(1).getValue()+"");
        this.getLblNumberCX().setText(this.getController().getCpu().getDataRegisters().get(2).getValue()+"");
        this.getLblNumberDX().setText(this.getController().getCpu().getDataRegisters().get(3).getValue()+"");
        this.getLblNumberAL().setText(this.getController().getCpu().getDataRegisters().get(1).getLowByteValue()+"");
        this.getLblNumberAH().setText(this.getController().getCpu().getDataRegisters().get(1).getHighByteValue()+"");
        
        this.getLblNumberAC().setText(this.getController().getCpu().getAccumulator()+"");
        if (this.getFileManager().getInstructions().size() > this.getController().getRowCount()+1){
            this.getLblNumberPC().setText(""+(this.getController().getCpu().getProgramCounter()+1));
            this.getLblNumberIR().setText(this.getFileManager().getInstructions().get(this.getController().getRowCount()).getAsmInstructionString());
        }
        else{
            this.getController().getCpu().setProgramCounter(Integer.parseInt(this.getLblNumberPC().getText()));
        }
        //
        
        //cpu 2
        
        //
        this.getController().setRowCount(this.getController().getRowCount()+1);
        this.getController().getCpu().setNumberExecutedInstructions(this.getController().getCpu().getNumberExecutedInstructions()+1);
        this.getController().getCpu().setCurrentAddress(this.getController().getCpu().getCurrentAddress()+1);
    } 

    public JTextPane getPantalla() {
        return pantalla;
    }

    public void setPantalla(JTextPane pantalla) {
        this.pantalla = pantalla;
    }

    public JTextField getTecladoTxtField() {
        return tecladoTxtField;
    }

    public void setTecladoTxtField(JTextField tecladoTxtField) {
        this.tecladoTxtField = tecladoTxtField;
    }
    
    

    public JLabel getLblNumberAH() {
        return lblNumberAH;
    }

    public void setLblNumberAH(JLabel lblNumberAH) {
        this.lblNumberAH = lblNumberAH;
    }

    public JLabel getLblNumberAL() {
        return lblNumberAL;
    }

    public void setLblNumberAL(JLabel lblNumberAL) {
        this.lblNumberAL = lblNumberAL;
    }
    
    

    public MiniPCController getController() {
        return controller;
    }

    public void setController(MiniPCController controller) {
        this.controller = controller;
    }
    
    
    public JTable getTblCode() {
        return tblCode;
    }

    public void setTblCode(JTable tblCode) {
        this.tblCode = tblCode;
    }

    
    
    public JLabel getLblNumberAC() {
        return lblNumberAC;
    }

    public void setLblNumberAC(JLabel lblNumberAC) {
        this.lblNumberAC = lblNumberAC;
    }

    public JLabel getLblNumberAX() {
        return lblNumberAX;
    }

    public void setLblNumberAX(JLabel lblNumberAX) {
        this.lblNumberAX = lblNumberAX;
    }

    public JLabel getLblNumberBX() {
        return lblNumberBX;
    }

    public void setLblNumberBX(JLabel lblNumberBX) {
        this.lblNumberBX = lblNumberBX;
    }

    public JLabel getLblNumberCX() {
        return lblNumberCX;
    }

    public void setLblNumberCX(JLabel lblNumberCX) {
        this.lblNumberCX = lblNumberCX;
    }

    public JLabel getLblNumberDX() {
        return lblNumberDX;
    }

    public void setLblNumberDX(JLabel lblNumberDX) {
        this.lblNumberDX = lblNumberDX;
    }

    public JLabel getLblNumberIR() {
        return lblNumberIR;
    }

    public void setLblNumberIR(JLabel lblNumberIR) {
        this.lblNumberIR = lblNumberIR;
    }

    public JLabel getLblNumberPC() {
        return lblNumberPC;
    }

    public void setLblNumberPC(JLabel lblNumberPC) {
        this.lblNumberPC = lblNumberPC;
    }

    public FileManager getFileManager() {
        return fileManager;
    }

    public void setFileManager(FileManager fileManager) {
        this.fileManager = fileManager;
    }

    
    
    private void nextInstructionBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextInstructionBtn1ActionPerformed

    private void loadFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileBtnActionPerformed
        if (evt.getSource() == loadFileBtn && !this.isWaitingForInput()) {
            //this.cleanTable();

            String filePath = fileManager.selectFile(this);
            fileManager.loadOperations();
            fileManager.loadDataRegisters();
            ArrayList<MemoryRegister> instructionSet = fileManager.loadFileInstructions(filePath);

            if (instructionSet.size() > 90){
                JOptionPane.showMessageDialog (null, "Hay más de 90 instrucciones por lo que no hay suficiente memoria para correrlas.", "Error: No hay suficiente memoria", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else if (instructionSet != null){
                Random rand = new Random();
                int cpuEscogido = 0;
                System.out.println("CPU escogido: #"+cpuEscogido);
                MiniPCController controller = null;
                
                if (cpuEscogido == 0){
                    controller = this.getController();
                }
                else if (cpuEscogido == 1){
                    controller = this.getController2();
                }
                
                Memory memory = controller.getCpu().getMemory();
                memory.setAllocatedSize(instructionSet.size());
                memory.allocateMemory(instructionSet);
                int processStartIndex = memory.getAllocationStartIndex();
                
                CPU cpu = controller.getCpu();
                
                StatsSet estadisticas = new StatsSet(cpu,cpu.getCurrentTime());
                BCP newBCP = new BCP(cpu.getMemory().getBcpList().size(),filePath,"Nuevo",processStartIndex+1,cpu.getMemory().getStack(),estadisticas,processStartIndex,instructionSet.size(),1);
                cpu.getMemory().getBcpList().add(newBCP);
                
                System.out.println("------------------------------------");
                System.out.println(newBCP.getAc());
                System.out.println(newBCP.getDataRegisters());
                System.out.println(newBCP.getDireccionInicio());
                System.out.println(newBCP.getEstadoActual());
                System.out.println(newBCP.getIdProcess());
                System.out.println(newBCP.getInformacionContable());
                System.out.println(newBCP.getNameProcess());
                System.out.println(newBCP.getPila());
                System.out.println(newBCP.getPrioridad());
                System.out.println(newBCP.getProgramCounter());
                System.out.println(newBCP.getTamanoProceso());
                System.out.println("------------------------------------");

                MemoryRegister currentInstruction = this.getFileManager().getInstructions().get(this.getController().getRowCount());
                controller.getCpu().setInstructionRegister(currentInstruction.getAsmInstructionString());
                controller.getCpu().setProgramCounter(controller.getCpu().getMemory().getAllocationStartIndex()+1);
                controller.getCpu().setCurrentAddress(controller.getCpu().getMemory().getAllocationStartIndex());
                newBCP.setEstadoActual("Preparado");
                System.out.println("PC: "+controller.getCpu().getProgramCounter());
                System.out.println("CA: "+controller.getCpu().getCurrentAddress());

                //try {
                //    controller.executeInstruction(currentInstruction.getOp(),currentInstruction.getRegister(),currentInstruction.getValue(),currentInstruction.getStringValue(),this);
                //} catch (InterruptedException ex) {
                //    Logger.getLogger(MiniPC.class.getName()).log(Level.SEVERE, null, ex);
               // }
                this.updateTable(this.fileManager.getInstructions(),this.fileManager.getInstructions2(),this.getController().getRowCount());
            }

        }
        else if (this.isWaitingForInput())
            JOptionPane.showMessageDialog (null, "Escriba un valor.", "Error: Debe escribir un valor.", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_loadFileBtnActionPerformed

    private void cleanTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanTableBtnActionPerformed
        if (this.getTblCode().getValueAt(0, 0) == "" || this.getTblCode().getValueAt(0, 0) == " "){
            JOptionPane.showMessageDialog (null, "No queda nada por limpiar", "Error: Archivo ya fue limpiado", JOptionPane.ERROR_MESSAGE);
        }
        else{
            this.setWaitingForInput(false);
            this.cleanTable();
            this.getPantalla().setText("");
        }
        
    }//GEN-LAST:event_cleanTableBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.setWaitingForInput(false);
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void nextInstructionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtnActionPerformed
        if (!this.isWaitingForInput()){
            if (this.getController().getCpu().getMemory().getBcpList().size() == 0 && this.getController2().getCpu().getMemory().getBcpList().size() == 0){
                JOptionPane.showMessageDialog (null, "Por favor cargue un archivo", "Error: Archivo no cargado", JOptionPane.ERROR_MESSAGE);
            }
            else if (this.getController().getCpu().getMemory().getBcpList().get(0).getEstadoActual().equalsIgnoreCase("Finalizado")){
                JOptionPane.showMessageDialog (null, "No quedan más instrucciones que cargar.", "Error: Final del archivo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                MemoryRegister currentInstruction = this.getFileManager().getInstructions().get(this.getController().getRowCount());
                this.getController().getCpu().setInstructionRegister(currentInstruction.getAsmInstructionString());
                System.out.println("test1");
                try {
                    this.getController().executeInstruction(currentInstruction.getOp(),currentInstruction.getRegister(),currentInstruction.getValue(),currentInstruction.getStringValue(),this);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MiniPC.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("test2");
                this.updateTable(this.fileManager.getInstructions(), this.fileManager.getInstructions2(),this.getController().getRowCount());
                this.getController().getCpu().setProgramCounter(this.getController().getCpu().getProgramCounter()+1);
            
                if (this.isJumpFlag()){
                    int nextInstructionAddress = this.getController().getCpu().getProgramCounter();
                    System.out.println("Vieja: "+nextInstructionAddress);
                    nextInstructionAddress = nextInstructionAddress+this.getJumpToAddress();
                    System.out.println("Nueva: "+nextInstructionAddress);
                    this.getController().getCpu().setCurrentAddress(nextInstructionAddress);
        
                    this.getController().getCpu().setProgramCounter(nextInstructionAddress);
                    this.getLblNumberPC().setText(nextInstructionAddress+"");
                    this.getController().setRowCount(this.getController().getRowCount()+this.getJumpToAddress());
                    this.setJumpFlag(false);
                }
            }
            
            if (this.getController().getRowCount() >= this.fileManager.getInstructions().size()){
                this.getController().getCpu().getMemory().getBcpList().get(0).setEstadoActual("Finalizado");
                this.getController().getCpu().getMemory().getBcpList().get(0).getInformacionContable().setEndTime(this.getController().getCpu().getCurrentTime());
                int startTime = this.getController().getCpu().getMemory().getBcpList().get(0).getInformacionContable().getStartTime();
                int endTime = this.getController().getCpu().getMemory().getBcpList().get(0).getInformacionContable().getEndTime();
                this.getController().getCpu().getMemory().getBcpList().get(0).getInformacionContable().setDurationTime(endTime-startTime);
                System.out.println("Start: "+startTime);
                System.out.println("End: "+endTime);
                System.out.println("Duration: "+this.getController().getCpu().getMemory().getBcpList().get(0).getInformacionContable().getDurationTime());
            }
        }
        else
            JOptionPane.showMessageDialog (null, "Escriba un valor.", "Error: Debe escribir un valor.", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_nextInstructionBtnActionPerformed

    private void tecladoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecladoTxtFieldActionPerformed
        System.out.println(this.getTecladoTxtField().getText());
        String inputTeclado = "";
        int valorTeclado = -1;
        inputTeclado = this.getTecladoTxtField().getText();
        
        if (inputTeclado.matches("-?\\d+(\\.\\d+)?")){
            valorTeclado = Integer.parseInt(inputTeclado);
            
            if (valorTeclado < 0 || valorTeclado > 255){
                JOptionPane.showMessageDialog (null, "Escriba un valor entre 0-255", "Error: Valor fuera del rango 0-255.", JOptionPane.ERROR_MESSAGE);
            }
            else{
                this.getController().getCpu().getDataRegisters().get(4-1).setValue(valorTeclado);
                this.getLblNumberDX().setText(valorTeclado+"");
                this.getTecladoTxtField().setEditable(false);
                this.setWaitingForInput(false);
                this.getTecladoTxtField().setText("");
            }
            
        }
        else{
            JOptionPane.showMessageDialog (null, "Escriba un valor entero.", "Error: Debe escribir un valor entero.", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_tecladoTxtFieldActionPerformed

    private void automaticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_automaticBtnActionPerformed

    private void cleanTableBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanTableBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanTableBtn1ActionPerformed

    private void cleanTableBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanTableBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanTableBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_memoria;
    private javax.swing.JLabel Lbl_memoria1;
    private javax.swing.JLabel Lbl_memoria2;
    private javax.swing.JLabel Lbl_memoria3;
    private javax.swing.JLabel Lbl_registros;
    private javax.swing.JLabel Lbl_registros1;
    private javax.swing.JScrollPane Pnl_Memoria;
    private javax.swing.JScrollPane Pnl_Memoria1;
    private javax.swing.JScrollPane Pnl_Memoria2;
    private javax.swing.JScrollPane Pnl_Memoria3;
    private javax.swing.JPanel Pnl_Menu;
    private javax.swing.JPanel Pnl_Registros;
    private javax.swing.JPanel Pnl_Registros1;
    private javax.swing.JButton automaticBtn;
    private javax.swing.JButton cleanTableBtn;
    private javax.swing.JButton cleanTableBtn1;
    private javax.swing.JButton cleanTableBtn2;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblAC1;
    private javax.swing.JLabel lblAH;
    private javax.swing.JLabel lblAH1;
    private javax.swing.JLabel lblAL;
    private javax.swing.JLabel lblAL1;
    private javax.swing.JLabel lblAX;
    private javax.swing.JLabel lblAX1;
    private javax.swing.JLabel lblBX;
    private javax.swing.JLabel lblBX1;
    private javax.swing.JLabel lblCX;
    private javax.swing.JLabel lblCX1;
    private javax.swing.JLabel lblDX;
    private javax.swing.JLabel lblDX1;
    private javax.swing.JLabel lblIR;
    private javax.swing.JLabel lblIR1;
    private javax.swing.JLabel lblNumberAC;
    private javax.swing.JLabel lblNumberAC1;
    private javax.swing.JLabel lblNumberAH;
    private javax.swing.JLabel lblNumberAH1;
    private javax.swing.JLabel lblNumberAL;
    private javax.swing.JLabel lblNumberAL1;
    private javax.swing.JLabel lblNumberAX;
    private javax.swing.JLabel lblNumberAX1;
    private javax.swing.JLabel lblNumberBX;
    private javax.swing.JLabel lblNumberBX1;
    private javax.swing.JLabel lblNumberCX;
    private javax.swing.JLabel lblNumberCX1;
    private javax.swing.JLabel lblNumberDX;
    private javax.swing.JLabel lblNumberDX1;
    private javax.swing.JLabel lblNumberIR;
    private javax.swing.JLabel lblNumberIR1;
    private javax.swing.JLabel lblNumberPC;
    private javax.swing.JLabel lblNumberPC1;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPC1;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblTeclado;
    private javax.swing.JButton loadFileBtn;
    private javax.swing.JButton nextInstructionBtn;
    private javax.swing.JButton nextInstructionBtn1;
    private javax.swing.JTextPane pantalla;
    private javax.swing.JTable tblCode;
    private javax.swing.JTable tblCode1;
    private javax.swing.JTable tblCode2;
    private javax.swing.JTable tblCode3;
    private javax.swing.JTextField tecladoTxtField;
    // End of variables declaration//GEN-END:variables
}
