/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MiniPCController;
import Model.BCP;
import Model.CPU;
import Model.FileManager;
import Model.Memory;
import Model.MemoryRegister;
import Model.StatsSet;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author aleja
 */
public class MiniPC extends javax.swing.JFrame {
    // Esta clase representa la GUI del programa que se utiliza para cargar los archivos, leer las instrucciones y ver la información de la memoria y los registros
    // Contiene el controlador del CPU, el administrador de archivos, la cantidad de filas de instrucciones que se han generado y la dirección actual que se desplegará en la GUI
    
    public MiniPCController controller = new MiniPCController();
    public MiniPCController controller2 = new MiniPCController();
    public FileManager fileManager = new FileManager();
    int rowCount = 0;
    int numberExecutedInstructions = -1;
    int currentAddress = 0;
    int time = 0;
    boolean waitingForInput = false;
    boolean archivoAbierto = false;
    boolean jumpFlag = false;
    int jumpToAddress = 0;
    
    /**
     * Creates new form NewJFrame
     */
    public MiniPC() {
        CPU cpu = new CPU("CPU #0");
        Memory memory = new Memory();
        cpu.setMemory(memory);
        
        CPU cpu2 = new CPU("CPU #1");
        Memory memory2 = new Memory();
        cpu2.setMemory(memory2);
        
        this.getController().setCpu(cpu);
        this.getController2().setCpu(cpu2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextInstructionBtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Pnl_Registros = new javax.swing.JPanel();
        lblAX = new javax.swing.JLabel();
        lblNumberAX = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        lblNumberPC = new javax.swing.JLabel();
        lblBX = new javax.swing.JLabel();
        lblNumberBX = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblNumberAC = new javax.swing.JLabel();
        lblCX = new javax.swing.JLabel();
        lblNumberCX = new javax.swing.JLabel();
        lblDX = new javax.swing.JLabel();
        lblNumberDX = new javax.swing.JLabel();
        lblIR = new javax.swing.JLabel();
        lblNumberIR = new javax.swing.JLabel();
        lblAL = new javax.swing.JLabel();
        lblNumberAL = new javax.swing.JLabel();
        lblAH = new javax.swing.JLabel();
        lblNumberAH = new javax.swing.JLabel();
        Pnl_Memoria = new javax.swing.JScrollPane();
        tblCode = new javax.swing.JTable();
        Pnl_Menu = new javax.swing.JPanel();
        loadFileBtn = new javax.swing.JButton();
        cleanTableBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        lblTeclado = new javax.swing.JLabel();
        nextInstructionBtn = new javax.swing.JButton();
        tecladoTxtField = new javax.swing.JTextField();
        lblPantalla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JTextPane();
        Lbl_memoria = new javax.swing.JLabel();
        Lbl_registros = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        nextInstructionBtn1.setText("Siguiente instrucción");
        nextInstructionBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniPC");

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 450));
        jPanel3.setRequestFocusEnabled(false);

        Pnl_Registros.setBackground(new java.awt.Color(204, 204, 255));

        lblAX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAX.setText("AX:");

        lblNumberAX.setText("0");

        lblPC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPC.setText("PC: ");

        lblNumberPC.setText("0");

        lblBX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBX.setText("BX:");

        lblNumberBX.setText("0");

        lblAC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAC.setText("AC:");

        lblNumberAC.setText("0");

        lblCX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCX.setText("CX:");

        lblNumberCX.setText("0");

        lblDX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDX.setText("DX: ");

        lblNumberDX.setText("0");

        lblIR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIR.setText("IR:");

        lblNumberIR.setText(" ");

        lblAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAL.setText("AL:");

        lblNumberAL.setText("0");

        lblAH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAH.setText("AH:");

        lblNumberAH.setText("0");

        javax.swing.GroupLayout Pnl_RegistrosLayout = new javax.swing.GroupLayout(Pnl_Registros);
        Pnl_Registros.setLayout(Pnl_RegistrosLayout);
        Pnl_RegistrosLayout.setHorizontalGroup(
            Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                        .addComponent(lblAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumberAL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                        .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAX)
                            .addComponent(lblPC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumberAX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumberPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAC)
                                    .addComponent(lblBX))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumberBX)
                                    .addComponent(lblNumberAC))
                                .addGap(35, 35, 35)
                                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                        .addComponent(lblIR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNumberIR, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                        .addComponent(lblCX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNumberCX)
                                        .addGap(32, 32, 32)
                                        .addComponent(lblDX)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNumberDX)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblAH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumberAH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        Pnl_RegistrosLayout.setVerticalGroup(
            Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RegistrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAX)
                    .addComponent(lblNumberAX)
                    .addComponent(lblBX)
                    .addComponent(lblNumberBX)
                    .addComponent(lblCX)
                    .addComponent(lblNumberCX)
                    .addComponent(lblDX)
                    .addComponent(lblNumberDX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC)
                    .addComponent(lblNumberPC)
                    .addComponent(lblAC)
                    .addComponent(lblNumberAC)
                    .addComponent(lblIR)
                    .addComponent(lblNumberIR))
                .addGap(7, 7, 7)
                .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAL)
                    .addComponent(lblNumberAL)
                    .addGroup(Pnl_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAH)
                        .addComponent(lblNumberAH)))
                .addContainerGap())
        );

        Pnl_Memoria.setBackground(new java.awt.Color(204, 204, 255));
        Pnl_Memoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pnl_Memoria.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pnl_Memoria.setMaximumSize(new java.awt.Dimension(102, 102));
        Pnl_Memoria.setMinimumSize(new java.awt.Dimension(101, 101));
        Pnl_Memoria.setName(""); // NOI18N

        tblCode.setBackground(new java.awt.Color(204, 204, 255));
        tblCode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código ASM", "Código binario", "Address", "Tiempo"
            }
        ));
        tblCode.setRowHeight(30);
        Pnl_Memoria.setViewportView(tblCode);

        Pnl_Menu.setBackground(new java.awt.Color(204, 204, 255));
        Pnl_Menu.setPreferredSize(new java.awt.Dimension(602, 602));

        loadFileBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        loadFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/archivo.png"))); // NOI18N
        loadFileBtn.setText("Cargar Archivo");
        loadFileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loadFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileBtnActionPerformed(evt);
            }
        });

        cleanTableBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cleanTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reiniciar.png"))); // NOI18N
        cleanTableBtn.setText("Limpiar");
        cleanTableBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cleanTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanTableBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salir.png"))); // NOI18N
        exitBtn.setText("Salir");
        exitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        lblTeclado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTeclado.setText("Teclado");

        nextInstructionBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nextInstructionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/siguiente.png"))); // NOI18N
        nextInstructionBtn.setText("Siguiente");
        nextInstructionBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nextInstructionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInstructionBtnActionPerformed(evt);
            }
        });

        tecladoTxtField.setEditable(false);
        tecladoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecladoTxtFieldActionPerformed(evt);
            }
        });

        lblPantalla.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPantalla.setText("Pantalla");

        jScrollPane1.setViewportView(pantalla);

        javax.swing.GroupLayout Pnl_MenuLayout = new javax.swing.GroupLayout(Pnl_Menu);
        Pnl_Menu.setLayout(Pnl_MenuLayout);
        Pnl_MenuLayout.setHorizontalGroup(
            Pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPantalla)
                .addGap(38, 38, 38))
            .addGroup(Pnl_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tecladoTxtField)
                    .addComponent(cleanTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextInstructionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFileBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTeclado)
                .addGap(40, 40, 40))
        );
        Pnl_MenuLayout.setVerticalGroup(
            Pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPantalla)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(loadFileBtn)
                .addGap(18, 18, 18)
                .addComponent(nextInstructionBtn)
                .addGap(18, 18, 18)
                .addComponent(cleanTableBtn)
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addGap(29, 29, 29)
                .addComponent(lblTeclado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tecladoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        Lbl_memoria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_memoria.setText("Memoria");
        Lbl_memoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_registros.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_registros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_registros.setText("Registros");
        Lbl_registros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Mini PC");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Pnl_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pnl_Memoria, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(Lbl_memoria))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lbl_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Pnl_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pnl_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_registros)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pnl_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Lbl_memoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pnl_Memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanTable(){
        // Este método limpia toda la tabla de instrucciones por medio de resetear todos los valores que están siendo actualmente desplegados
        // También resetea el controlador de CPU actual y el administrador de archivos actual
        // No recibe ningún parámetro
        
        for (int i = 0; i < this.getTblCode().getRowCount(); i++) {
                this.getTblCode().setValueAt("", i, 0);
                this.getTblCode().setValueAt("", i, 1);
                this.getTblCode().setValueAt("", i, 2);
                this.getTblCode().setValueAt("", i, 3);
        }
        this.getLblNumberAC().setText("0");
        this.getLblNumberPC().setText("0");
        this.getLblNumberIR().setText(" ");
        this.getLblNumberAX().setText("0");
        this.getLblNumberBX().setText("0");
        this.getLblNumberCX().setText("0");
        this.getLblNumberDX().setText("0");
        this.setRowCount(0);
        this.setNumberExecutedInstructions(-1);
        this.setCurrentAddress(0);
        this.getController().setCpu(null);
        FileManager newFileManager = new FileManager();
        this.setFileManager(newFileManager);
    }

    public boolean isJumpFlag() {
        return jumpFlag;
    }

    public void setJumpFlag(boolean jumpFlag) {
        this.jumpFlag = jumpFlag;
    }

    public int getJumpToAddress() {
        return jumpToAddress;
    }

    public void setJumpToAddress(int jumpToAddress) {
        this.jumpToAddress = jumpToAddress;
    }
    
    

    public int getNumberExecutedInstructions() {
        return numberExecutedInstructions;
    }

    public void setNumberExecutedInstructions(int numberExecutedInstructions) {
        this.numberExecutedInstructions = numberExecutedInstructions;
    }

    public boolean isWaitingForInput() {
        return waitingForInput;
    }

    public void setWaitingForInput(boolean waitingForInput) {
        this.waitingForInput = waitingForInput;
    }

    public boolean isArchivoAbierto() {
        return archivoAbierto;
    }

    public void setArchivoAbierto(boolean archivoAbierto) {
        this.archivoAbierto = archivoAbierto;
    }

    public MiniPCController getController2() {
        return controller2;
    }

    public void setController2(MiniPCController controller2) {
        this.controller2 = controller2;
    }
    
    
    
    public void updateTable(ArrayList<MemoryRegister> instructionSet, int row) {
        // Este método actualiza la tabla visualmente, es decir actualiza la información que está siendo desplegada en la GUI
        // Va mostrando paso a paso las instrucciones cargadas en memoria y toda la información relevante a estas
        // Recibe como parámetros el set de instrucciones y el valor entero de la fila donde se desplegará la instrucción
        
        this.getTblCode().setValueAt(instructionSet.get(row).getAsmInstructionString(), this.getNumberExecutedInstructions(), 0);
        this.getTblCode().setValueAt(instructionSet.get(row).convertToBinary(), this.getNumberExecutedInstructions(), 1);
        this.getTblCode().setValueAt(this.getCurrentAddress(), this.getNumberExecutedInstructions(), 2);
        this.getTblCode().setValueAt(this.getTime(), this.getNumberExecutedInstructions(), 3);
        
        this.getLblNumberAX().setText(this.getController().getCpu().getDataRegisters().get(0).getValue()+"");
        this.getLblNumberBX().setText(this.getController().getCpu().getDataRegisters().get(1).getValue()+"");
        this.getLblNumberCX().setText(this.getController().getCpu().getDataRegisters().get(2).getValue()+"");
        this.getLblNumberDX().setText(this.getController().getCpu().getDataRegisters().get(3).getValue()+"");
        this.getLblNumberAL().setText(this.getController().getCpu().getDataRegisters().get(1).getLowByteValue()+"");
        this.getLblNumberAH().setText(this.getController().getCpu().getDataRegisters().get(1).getHighByteValue()+"");
        
        this.getLblNumberAC().setText(this.getController().getCpu().getAccumulator()+"");
        if (this.getFileManager().getInstructions().size() > this.getRowCount()+1){
            this.getLblNumberPC().setText(""+(this.getCurrentAddress()+1));
            this.getLblNumberIR().setText(this.getFileManager().getInstructions().get(this.getRowCount()).getAsmInstructionString());
        }
        else{
            this.getController().getCpu().setProgramCounter(Integer.parseInt(this.getLblNumberPC().getText()));
        }
        
        this.setRowCount(this.getRowCount()+1);
        this.setCurrentAddress(this.getCurrentAddress()+1);
    } 

    public int getTime() {
        return time;
    }

    public void setTime(int time) {
        this.time = time;
    }
    
    

    public JTextPane getPantalla() {
        return pantalla;
    }

    public void setPantalla(JTextPane pantalla) {
        this.pantalla = pantalla;
    }

    public JTextField getTecladoTxtField() {
        return tecladoTxtField;
    }

    public void setTecladoTxtField(JTextField tecladoTxtField) {
        this.tecladoTxtField = tecladoTxtField;
    }
    
    

    public JLabel getLblNumberAH() {
        return lblNumberAH;
    }

    public void setLblNumberAH(JLabel lblNumberAH) {
        this.lblNumberAH = lblNumberAH;
    }

    public JLabel getLblNumberAL() {
        return lblNumberAL;
    }

    public void setLblNumberAL(JLabel lblNumberAL) {
        this.lblNumberAL = lblNumberAL;
    }
    
    

    public MiniPCController getController() {
        return controller;
    }

    public void setController(MiniPCController controller) {
        this.controller = controller;
    }

    public int getCurrentAddress() {
        return currentAddress;
    }

    public void setCurrentAddress(int currentAddress) {
        this.currentAddress = currentAddress;
    }

    
    
    public int getRowCount() {
        return rowCount;
    }

    public void setRowCount(int rowCount) {
        this.rowCount = rowCount;
    }
    
    
    
    public JTable getTblCode() {
        return tblCode;
    }

    public void setTblCode(JTable tblCode) {
        this.tblCode = tblCode;
    }

    
    
    public JLabel getLblNumberAC() {
        return lblNumberAC;
    }

    public void setLblNumberAC(JLabel lblNumberAC) {
        this.lblNumberAC = lblNumberAC;
    }

    public JLabel getLblNumberAX() {
        return lblNumberAX;
    }

    public void setLblNumberAX(JLabel lblNumberAX) {
        this.lblNumberAX = lblNumberAX;
    }

    public JLabel getLblNumberBX() {
        return lblNumberBX;
    }

    public void setLblNumberBX(JLabel lblNumberBX) {
        this.lblNumberBX = lblNumberBX;
    }

    public JLabel getLblNumberCX() {
        return lblNumberCX;
    }

    public void setLblNumberCX(JLabel lblNumberCX) {
        this.lblNumberCX = lblNumberCX;
    }

    public JLabel getLblNumberDX() {
        return lblNumberDX;
    }

    public void setLblNumberDX(JLabel lblNumberDX) {
        this.lblNumberDX = lblNumberDX;
    }

    public JLabel getLblNumberIR() {
        return lblNumberIR;
    }

    public void setLblNumberIR(JLabel lblNumberIR) {
        this.lblNumberIR = lblNumberIR;
    }

    public JLabel getLblNumberPC() {
        return lblNumberPC;
    }

    public void setLblNumberPC(JLabel lblNumberPC) {
        this.lblNumberPC = lblNumberPC;
    }

    public FileManager getFileManager() {
        return fileManager;
    }

    public void setFileManager(FileManager fileManager) {
        this.fileManager = fileManager;
    }

    
    
    private void nextInstructionBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextInstructionBtn1ActionPerformed

    private void loadFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileBtnActionPerformed
        if (evt.getSource() == loadFileBtn && !this.isWaitingForInput()) {
            //this.cleanTable();

            String filePath = fileManager.selectFile(this);
            fileManager.loadOperations();
            fileManager.loadDataRegisters();
            ArrayList<MemoryRegister> instructionSet = fileManager.loadFileInstructions(filePath);

            if (instructionSet.size() > 90){
                JOptionPane.showMessageDialog (null, "Hay más de 90 instrucciones por lo que no hay suficiente memoria para correrlas.", "Error: No hay suficiente memoria", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else if (instructionSet != null){
                Random rand = new Random();
                int cpuEscogido = rand.nextInt(1 - 0 + 1) + 0;
                System.out.println("CPU escogido: #"+cpuEscogido);
                MiniPCController controller = null;
                
                if (cpuEscogido == 0){
                    controller = this.getController();
                }
                else if (cpuEscogido == 1){
                    controller = this.getController2();
                }
                
                Memory memory = controller.getCpu().getMemory();
                memory.setAllocatedSize(instructionSet.size());
                memory.allocateMemory(instructionSet);
                int processStartIndex = memory.getAllocationStartIndex();
                
                CPU cpu = controller.getCpu();
                
                StatsSet estadisticas = new StatsSet(cpu,cpu.getCurrentTime());
                BCP newBCP = new BCP(cpu.getMemory().getBcpList().size(),filePath,"Nuevo",processStartIndex+1,cpu.getMemory().getStack(),estadisticas,processStartIndex,instructionSet.size(),1);
                
                System.out.println("------------------------------------");
                System.out.println(newBCP.getAc());
                System.out.println(newBCP.getDataRegisters());
                System.out.println(newBCP.getDireccionInicio());
                System.out.println(newBCP.getEstadoActual());
                System.out.println(newBCP.getIdProcess());
                System.out.println(newBCP.getInformacionContable());
                System.out.println(newBCP.getNameProcess());
                System.out.println(newBCP.getPila());
                System.out.println(newBCP.getPrioridad());
                System.out.println(newBCP.getProgramCounter());
                System.out.println(newBCP.getTamanoProceso());
                System.out.println("------------------------------------");
                
                this.setCurrentAddress(controller.getCpu().getMemory().getAllocationStartIndex());

                MemoryRegister currentInstruction = this.getFileManager().getInstructions().get(this.getRowCount());
                controller.getCpu().setInstructionRegister(currentInstruction.getAsmInstructionString());
                controller.getCpu().setProgramCounter(this.currentAddress);

                try {
                    controller.executeInstruction(currentInstruction.getOp(),currentInstruction.getRegister(),currentInstruction.getValue(),currentInstruction.getStringValue(),this);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MiniPC.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.updateTable(this.fileManager.getInstructions(),this.getRowCount());
            }

        }
        else if (this.isWaitingForInput())
            JOptionPane.showMessageDialog (null, "Escriba un valor.", "Error: Debe escribir un valor.", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_loadFileBtnActionPerformed

    private void cleanTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanTableBtnActionPerformed
        if (this.getTblCode().getValueAt(0, 0) == "" || this.getTblCode().getValueAt(0, 0) == " "){
            JOptionPane.showMessageDialog (null, "No queda nada por limpiar", "Error: Archivo ya fue limpiado", JOptionPane.ERROR_MESSAGE);
        }
        else{
            this.setWaitingForInput(false);
            this.cleanTable();
            this.getPantalla().setText("");
        }
        
    }//GEN-LAST:event_cleanTableBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.setWaitingForInput(false);
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void nextInstructionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInstructionBtnActionPerformed
        if (!this.isWaitingForInput()){
            if (this.getController().getCpu() == null && this.getController2().getCpu() == null){
                JOptionPane.showMessageDialog (null, "Por favor cargue un archivo", "Error: Archivo no cargado", JOptionPane.ERROR_MESSAGE);
            }
            else if (this.getRowCount() >= this.fileManager.getInstructions().size()){
                JOptionPane.showMessageDialog (null, "No quedan más instrucciones que cargar.", "Error: Final del archivo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                MemoryRegister currentInstruction = this.getFileManager().getInstructions().get(this.getRowCount());
                this.getController().getCpu().setInstructionRegister(currentInstruction.getAsmInstructionString());
                System.out.println("test1");
                try {
                    this.getController().executeInstruction(currentInstruction.getOp(),currentInstruction.getRegister(),currentInstruction.getValue(),currentInstruction.getStringValue(),this);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MiniPC.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("test2");
                this.updateTable(this.fileManager.getInstructions(), this.getRowCount());
                this.getController().getCpu().setProgramCounter(this.getCurrentAddress());
            
                if (this.isJumpFlag()){
                    int nextInstructionAddress = this.getController().getCpu().getProgramCounter();
                    System.out.println("Vieja: "+nextInstructionAddress);
                    nextInstructionAddress = nextInstructionAddress+this.getJumpToAddress();
                    System.out.println("Nueva: "+nextInstructionAddress);
                    this.setCurrentAddress(nextInstructionAddress);
        
                    this.getController().getCpu().setProgramCounter(nextInstructionAddress);
                    this.getLblNumberPC().setText(nextInstructionAddress+"");
                    this.setRowCount(this.getRowCount()+this.getJumpToAddress());
                    this.setJumpFlag(false);
                }
            }
        }
        else
            JOptionPane.showMessageDialog (null, "Escriba un valor.", "Error: Debe escribir un valor.", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_nextInstructionBtnActionPerformed

    private void tecladoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecladoTxtFieldActionPerformed
        System.out.println(this.getTecladoTxtField().getText());
        String inputTeclado = "";
        int valorTeclado = -1;
        inputTeclado = this.getTecladoTxtField().getText();
        
        if (inputTeclado.matches("-?\\d+(\\.\\d+)?")){
            valorTeclado = Integer.parseInt(inputTeclado);
            
            if (valorTeclado < 0 || valorTeclado > 255){
                JOptionPane.showMessageDialog (null, "Escriba un valor entre 0-255", "Error: Valor fuera del rango 0-255.", JOptionPane.ERROR_MESSAGE);
            }
            else{
                this.getController().getCpu().getDataRegisters().get(4-1).setValue(valorTeclado);
                this.getLblNumberDX().setText(valorTeclado+"");
                this.getTecladoTxtField().setEditable(false);
                this.setWaitingForInput(false);
                this.getTecladoTxtField().setText("");
            }
            
        }
        else{
            JOptionPane.showMessageDialog (null, "Escriba un valor entero.", "Error: Debe escribir un valor entero.", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_tecladoTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_memoria;
    private javax.swing.JLabel Lbl_registros;
    private javax.swing.JScrollPane Pnl_Memoria;
    private javax.swing.JPanel Pnl_Menu;
    private javax.swing.JPanel Pnl_Registros;
    private javax.swing.JButton cleanTableBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblAH;
    private javax.swing.JLabel lblAL;
    private javax.swing.JLabel lblAX;
    private javax.swing.JLabel lblBX;
    private javax.swing.JLabel lblCX;
    private javax.swing.JLabel lblDX;
    private javax.swing.JLabel lblIR;
    private javax.swing.JLabel lblNumberAC;
    private javax.swing.JLabel lblNumberAH;
    private javax.swing.JLabel lblNumberAL;
    private javax.swing.JLabel lblNumberAX;
    private javax.swing.JLabel lblNumberBX;
    private javax.swing.JLabel lblNumberCX;
    private javax.swing.JLabel lblNumberDX;
    private javax.swing.JLabel lblNumberIR;
    private javax.swing.JLabel lblNumberPC;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblTeclado;
    private javax.swing.JButton loadFileBtn;
    private javax.swing.JButton nextInstructionBtn;
    private javax.swing.JButton nextInstructionBtn1;
    private javax.swing.JTextPane pantalla;
    private javax.swing.JTable tblCode;
    private javax.swing.JTextField tecladoTxtField;
    // End of variables declaration//GEN-END:variables
}
